"""Show what each lesson asks the student to do, one change at a time.

The answer pages under source/answers/ are grouped by file: what each lesson's
patch changes in it. This groups by lesson instead: a page per lesson, holding
the files it copies and every change its patches make, wherever they land. L6
copies two files and changes three, and all of it is on the L6 page.

Everything comes from applying solutions/ in order, by tools/applied.py, the
same as the answer pages. Each change is shown as the diff that making it does,
starting from the file as the lesson's copies left it and applying one change at
a time, so the context lines already carry the changes before it. Read down a
page and you see the edits in the order a student makes them. Changes made only
of comments are shown too, and labelled, because a page that tells a student
where to put code has to account for every line that moves.

Applying the changes in order has to reproduce the file the patch produced, and
the tool checks that it does.

The pages are generated and not committed: this is a view for reading, not part
of the guide a student reads. `--build` runs Sphinx over them and prints where
the HTML landed.
"""

import argparse
import difflib
import re
import subprocess
import sys
from pathlib import Path

import answers
from applied import Copied, apply_all
from bookpaths import book_root

OUT = "review"

CONF = '''"""Generated by tools/diffs.py. Edits here are overwritten."""

project = "What the student writes"
html_title = "What the student writes"
extensions = ["myst_parser"]
myst_enable_extensions = ["colon_fence", "deflist"]
html_theme = "furo"
'''

MARKER = re.compile(r"TODO(\s+(?P<number>\d+))?")
COMMENTS_ONLY = "Comments only"


def heading(block: list[str], is_code: bool) -> str:
    """Every TODO marker in one run of changed lines, for the section title.

    The whole run is one edit and can hold several markers, so all of them are
    named. A run holding no marker is a change a lesson makes to a file it grew
    from an earlier one, or a line difflib put beside a blank rather than in it.
    """
    numbers = []
    for line in block:
        for found in MARKER.finditer(line):
            number = found.group("number")
            if number is not None and number not in numbers:
                numbers.append(number)
    if not numbers:
        return "A change" if is_code else COMMENTS_ONLY
    if len(numbers) == 1:
        return "TODO " + numbers[0]
    return "TODO " + ", ".join(numbers[:-1]) + " and " + numbers[-1]


def steps(before: list[str], after: list[str]) -> tuple[list[dict], list[str]]:
    """Each change made in turn, with the diff it makes.

    Making one changes how many lines the file has, so every change after it sits
    somewhere else than the alignment said. The running offset is that
    difference, which is why they are applied forwards: forwards is the order a
    student works in, and the context lines have to look like what they see.
    """
    state = list(before)
    offset = 0
    out = []
    for i1, i2, j1, j2, is_code in answers.differences(before, after):
        was = list(state)
        state[i1 + offset:i2 + offset] = after[j1:j2]
        offset += (j2 - j1) - (i2 - i1)
        out.append({
            "name": heading(before[i1:i2], is_code),
            "code": is_code,
            "deleted": i2 - i1,
            "written": j2 - j1,
            "diff": "\n".join(difflib.unified_diff(
                was, list(state), lineterm="", n=3,
                fromfile="before this change", tofile="after it")),
        })
    return out, state


def lines(count: int, what: str) -> str:
    return f"{count} {what}line" + ("" if count == 1 else "s")


def page(lesson: str, copies: list[Copied], files: list[tuple[str, list[dict]]]) -> str:
    changes = sum(len(group) for _, group in files)
    written = sum(s["written"] for _, group in files for s in group if s["code"])
    out = [f"# {lesson}", ""]
    out.append(f"{len(copies)} file(s) copied, then {changes} change(s) in {len(files)} file(s), "
               f"{written} line(s) of code to write.")
    out.append("")
    if copies:
        out.append("## Copies")
        out.append("")
        for c in copies:
            out.append(f"- `{c.source}` to `{c.target}`")
        out.append("")
    for path, group in files:
        out.append(f"## {Path(path).stem}")
        out.append("")
        out.append(f"`{path}`")
        out.append("")
        for s in group:
            out.append(f"### {s['name']}")
            out.append("")
            out.append(f"Delete {lines(s['deleted'], '')}, write {lines(s['written'], '')}.")
            out.append("")
            out.append("```diff")
            out.append(s["diff"])
            out.append("```")
            out.append("")
    if not files:
        out.append("No patch: the copies are the whole lesson.")
        out.append("")
    return "\n".join(out)


def index(rows: list[tuple], solutions: str, wrong: list[str]) -> str:
    out = ["# What the student writes", ""]
    out.append(f"Every lesson's copies and patches, from applying `solutions/` on `{solutions}` in")
    out.append("order. Each page is one lesson, each section one file, and each diff is one edit")
    out.append("a student makes, comments included.")
    out.append("")
    out.append("The edits are grouped by where the two sides of a patch differ, not by the TODO")
    out.append("numbering, so a run holding three markers is one edit and is named after all three.")
    out.append("")
    out.append("| Lesson | Copies | Files changed | Changes | Lines of code to write |")
    out.append("| --- | --- | --- | --- | --- |")
    for lesson, copies, files, changes, written in rows:
        out.append(f"| [{lesson}]({lesson}.md) | {copies} | {files} | {changes} | {written} |")
    out.append(f"| **Total** | | | **{sum(r[3] for r in rows)}** | **{sum(r[4] for r in rows)}** |")
    out.append("")
    if wrong:
        out.append("These files did not come out the same as their patch left them after every")
        out.append("change was applied, so something below is wrong: " + ", ".join(wrong) + ".")
    else:
        out.append("Applying every change in order reproduces what each patch left, which is checked")
        out.append("each time this is generated.")
    out.append("")
    out.append("```{toctree}")
    out.append(":maxdepth: 1")
    out.append(":hidden:")
    out.append("")
    for row in rows:
        out.append(row[0])
    out.append("```")
    out.append("")
    return "\n".join(out)


def generate(solutions: str) -> tuple[dict[str, str], list[str]]:
    patched, _, copied = apply_all(solutions)
    # Both lists come back in the order applied, and every lesson copies before it patches.
    order = list(dict.fromkeys([c.lesson for c in copied] + [p.lesson for p in patched]))
    wrong = []
    pages = {}
    rows = []
    for lesson in order:
        files: list[tuple[str, list[dict]]] = []
        for patch in (p for p in patched if p.lesson == lesson):
            made, arrived = steps(patch.before, patch.after)
            if arrived != patch.after:
                wrong.append(f"{Path(patch.path).stem} in {answers.label(lesson)}")
            files.append((patch.path, made))
        copies = [c for c in copied if c.lesson == lesson]
        name = answers.label(lesson)
        pages[name + ".md"] = page(name, copies, files)
        rows.append((name, len(copies), len(files),
                     sum(len(group) for _, group in files),
                     sum(s["written"] for _, group in files for s in group if s["code"])))
    pages["index.md"] = index(rows, solutions, wrong)
    pages["conf.py"] = CONF
    return pages, wrong


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _, pinned = answers.pins()
    parser.add_argument("--solutions", default=pinned,
                        help=f"the solutions ref to apply (default {pinned}, from keep.toml)")
    parser.add_argument("--build", action="store_true", help="run Sphinx over the pages")
    args = parser.parse_args()

    out = book_root() / OUT / "source"
    pages, wrong = generate(args.solutions)
    out.mkdir(parents=True, exist_ok=True)
    for stale in out.glob("*.md"):
        if stale.name not in pages:
            stale.unlink()
    for name, text in pages.items():
        (out / name).write_text(text, encoding="utf-8")
    changes = sum(text.count("\n### ") for name, text in pages.items() if name != "index.md")
    print(f"{changes} change(s) across {len(pages) - 2} lesson(s), into {OUT}/source")

    if wrong:
        print("\nApplying every change did not reproduce what the patch left for: "
              + ", ".join(wrong))
        return 1

    if args.build:
        html = book_root() / OUT / "build" / "html"
        finished = subprocess.run(
            ["sphinx-build", "-W", "-b", "html", str(out), str(html)],
            cwd=book_root(),
        )
        if finished.returncode:
            return finished.returncode
        print(f"\nOpen {html / 'index.html'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
